#!/bin/bash

connection=$(nmcli d | awk 'FNR == 2 {print $2}')
state=$(nmcli d | awk 'FNR == 2 {print $3}')

if [ $connection == "ethernet" ]; then
	if [ $state == "connected" ]; then
		echo " [up]"
	else
		echo " [down]"
	fi
elif [ $connection == "wifi" ]; then
	if [ $state == "connected" ]; then
		echo " [up]"
	else
		echo " [down]"
	fi
fi
