#!/bin/bash

mono=$(amixer -M sget Master | grep Mono: | awk '{ print $2 }')

if [ -z "$mono" ]; then
	muted=$(amixer -M sget Master | awk 'FNR == 6 { print $7 }' | sed 's/[][]//g')
	vol=$(amixer -M sget Master | awk 'FNR == 6 { print $5 }' | sed 's/[][]//g; s/%//g')
else
	muted=$(amixer -M sget Master | awk 'FNR == 5 { print $6 }' | sed 's/[][]//g')
	vol=$(amixer -M sget Master | awk 'FNR == 5 { print $4 }' | sed 's/[][]//g; s/%//g')
fi
	if [ "$muted" = "off" ]; then
		echo " [muted]"
	else
	if [ "$vol" -ge 65 ]; then
		echo " [$vol%]"
	elif [ "$vol" -ge 40 ]; then
		echo " [$vol%]"
	elif [ "$vol" -ge 0 ]; then
		echo " [$vol%]"	
	fi
fi